
spring:
  datasource:
    url: 'jdbc:log4jdbc:mysql://192.168.1.11:3306/sql-flow?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false'
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password: YouCon123!
  jpa:
    hibernate:
      ddl-auto: update